name: Build and Release Application Files

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore "ESP Flasher/ESP flasher.csproj"

    - name: Build solution
      run: dotnet build "ESP Flasher/ESP flasher.csproj" --configuration Release

    - name: Publish the application (Portable)
      run: dotnet publish "ESP Flasher/ESP flasher.csproj" -c Release -o ./publish/portable

    - name: Create zip archive (Portable)
      run: |
        powershell Compress-Archive -Path ./publish/portable/* -DestinationPath ./ESPFlasher_Portable.zip

    - name: Publish the application (ClickOnce)
      run: dotnet publish "ESP Flasher/ESP flasher.csproj" -c Release /p:PublishProfile=ClickOnceProfile

    - name: Create zip archive (ClickOnce)
      run: |
        powershell Compress-Archive -Path "ESP Flasher/bin/Release/net8.0-windows/publish/*" -DestinationPath ./ESPFlasher_ClickOnce.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: notes/${{ github.ref_name }}.md  # Reference the correct release notes file based on the tag
        draft: false
        prerelease: false

    - name: Upload Portable Version
      id: upload-release-asset-portable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ESPFlasher_Portable.zip
        asset_name: ESPFlasher_Portable.zip
        asset_content_type: application/zip
        label: "ESP Flasher Portable Version"

    - name: Upload ClickOnce Installer
      id: upload-release-asset-clickonce
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ESPFlasher_ClickOnce.zip
        asset_name: ESPFlasher_ClickOnce.zip
        asset_content_type: application/zip
        label: "ESP Flasher ClickOnce Installer"
